doma:
  dialect: postgres

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/kotlindemo
spring.datasource.username: postgres
spring.datasource.password:
